version: '3.1'

services:
  aeon-docker:
    image: aeonpocket/rpc
    environment:
      - DAEMON_HOST=192.168.2.110
      - DAEMON_PORT=11181
    deploy:
      replicas: 3
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    volumes:
      - /home/aeon/redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aeon
      - MONGO_INITDB_ROOT_PASSWORD=P@ssword1
      - MONGO_INITDB_DATABASE=aeon
    volumes:
      - /home/aeon/db:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  php-wallet:
    image: aeonpocket/web-wallet
    depends_on:
      - mongo
      - aeon-docker
      - redis
    environment:
      - APP_URL=https://localhost
      - APP_KEY=base64:8lMo2Gphbny1XQjS/Rv8gLdNCk5Saqt9agkYIfK7Il0=
      - APP_LOG=errorlog
      - APP_RPC_URL=http://aeon-docker:11191/json_rpc
      - DB_CONNECTION=mongodb
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=aeon
      - MONGO_DB_USERNAME=aeon
      - MONGO_DB_PASSWORD=P@ssword1
      - MONGO_DB_MAIN_DB=admin
    volumes:
      - ./conf:/etc/apache2/sites-enabled
      - /home/aeon/ssl:/root/ssl
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3