version: '2'

services:
  php-wallet:
    image: pushkar8723/php-wallet
    depends_on:
      - mongo
      - aeon-docker
      - redis
    environment:
      - APP_URL=https://localhost
      - APP_KEY=base64:8lMo2Gphbny1XQjS/Rv8gLdNCk5Saqt9agkYIfK7Il0=
      - APP_LOG=errorlog
      - APP_RPC_URL=http://aeon-docker:11191/json_rpc
      - DB_CONNECTION=mongodb
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=aeon
      - MONGO_DB_USERNAME=aeon
      - MONGO_DB_PASSWORD=P@ssword1
      - MONGO_DB_MAIN_DB=admin
    volumes:
      - ./conf:/etc/apache2/sites-enabled
      - /home/aeon/ssl:/root/ssl
      - ./src:/var/www/html
    ports:
      - 80:80
      - 443:443

  aeon-docker:
    image: pushkar8723/aeon-docker
    environment:
      - DAEMON_HOST=192.168.2.108
      - DAEMON_PORT=11181

  redis:
    image: redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aeon
      - MONGO_INITDB_ROOT_PASSWORD=P@ssword1
      - MONGO_INITDB_DATABASE=aeon
    volumes:
      - /home/aeon/db:/data/db
    ports:
      - 27017:27017